<?php
namespace Rest_Buddy;

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class RESTBuddy
{
    private $rest_buddy_options;

    public function __construct()
    {
        add_action('admin_menu', array($this, 'rest_buddy_add_plugin_page'));
        add_action('admin_init', array($this, 'rest_buddy_page_init'));
    }

    public function rest_buddy_add_plugin_page()
    {
        add_options_page(
            'REST Buddy', // page_title
            'REST Buddy', // menu_title
            'manage_options', // capability
            'rest-buddy', // menu_slug
            array($this, 'rest_buddy_create_admin_page') // function
        );
    }

    public function rest_buddy_create_admin_page()
    {
        $this->rest_buddy_options = get_option('rest_buddy_option_name'); ?>

        <div class="wrap">
            <h2>REST Buddy</h2>
            <p>REST Buddy Settings</p>
            <?php settings_errors(); ?>

            <form method="post" action="options.php">
                <?php
                settings_fields('rest_buddy_option_group');
                do_settings_sections('rest-buddy-admin');
                submit_button();
                ?>
            </form>
        </div>
    <?php }

    public function rest_buddy_page_init()
    {
        register_setting(
            'rest_buddy_option_group', // option_group
            'rest_buddy_option_name', // option_name
            array($this, 'rest_buddy_sanitize') // sanitize_callback
        );

        add_settings_section(
            'rest_buddy_setting_section', // id
            'Settings', // title
            array($this, 'rest_buddy_section_info'), // callback
            'rest-buddy-admin' // page
        );

        add_settings_field(
            'menus_in_public_rest_0', // id
            'Menus in public REST', // title
            array($this, 'menus_in_public_rest_0_callback'), // callback
            'rest-buddy-admin', // page
            'rest_buddy_setting_section' // section
        );

        add_settings_field(
            'block_in_rest_1', // id
            'Block in REST', // title
            array($this, 'block_in_rest_1_callback'), // callback
            'rest-buddy-admin', // page
            'rest_buddy_setting_section' // section
        );

        add_settings_field(
            'featured_image_in_rest_2', // id
            'Featured Image in REST', // title
            array($this, 'featured_image_in_rest_2_callback'), // callback
            'rest-buddy-admin', // page
            'rest_buddy_setting_section' // section
        );
    }

    public function rest_buddy_sanitize($input)
    {
        $sanitary_values = array();
        if (isset($input['menus_in_public_rest_0'])) {
            $sanitary_values['menus_in_public_rest_0'] = $input['menus_in_public_rest_0'];
        }

        if (isset($input['block_in_rest_1'])) {
            $sanitary_values['block_in_rest_1'] = $input['block_in_rest_1'];
        }

        if (isset($input['featured_image_in_rest_2'])) {
            $sanitary_values['featured_image_in_rest_2'] = $input['featured_image_in_rest_2'];
        }

        return $sanitary_values;
    }

    public function rest_buddy_section_info()
    {
        $urls = [
            [
                'url' => site_url() . "/wp-json/wp/v2/pages?slug=sample-page",
                'label' => 'Page'
            ],
            [
                'url' => site_url() . "/wp-json/rest-buddy/v1/menu-location",
                'label' => 'Menu Locations'
            ],
            [
                'url' => site_url() . "/wp-json/rest-buddy/v1/menu-location?name=header-menu",
                'label' => 'Menu'
            ],
        ];
        foreach ($urls as $link) : ?>
        <ul>
            <li><?=$link['label']?>: <a href="<?=$link['url']?>" target="_blank"><?=$link['url']?></a></li>
        </ul>
        <?php endforeach;
    }

    public function menus_in_public_rest_0_callback()
    {
    ?> <fieldset><?php $checked = (isset($this->rest_buddy_options['menus_in_public_rest_0']) && $this->rest_buddy_options['menus_in_public_rest_0'] === 'Yes') ? 'checked' : ''; ?>
            <label for="menus_in_public_rest_0-0"><input type="radio" name="rest_buddy_option_name[menus_in_public_rest_0]" id="menus_in_public_rest_0-0" value="Yes" <?php echo $checked; ?>> Yes</label><br>
            <?php $checked = (isset($this->rest_buddy_options['menus_in_public_rest_0']) && $this->rest_buddy_options['menus_in_public_rest_0'] === 'No') ? 'checked' : ''; ?>
            <label for="menus_in_public_rest_0-1"><input type="radio" name="rest_buddy_option_name[menus_in_public_rest_0]" id="menus_in_public_rest_0-1" value="No" <?php echo $checked; ?>> No</label>
        </fieldset> <?php
                }

                public function block_in_rest_1_callback()
                {
                    ?> <fieldset><?php $checked = (isset($this->rest_buddy_options['block_in_rest_1']) && $this->rest_buddy_options['block_in_rest_1'] === 'Yes') ? 'checked' : ''; ?>
            <label for="block_in_rest_1-0"><input type="radio" name="rest_buddy_option_name[block_in_rest_1]" id="block_in_rest_1-0" value="Yes" <?php echo $checked; ?>> Yes</label><br>
            <?php $checked = (isset($this->rest_buddy_options['block_in_rest_1']) && $this->rest_buddy_options['block_in_rest_1'] === 'No') ? 'checked' : ''; ?>
            <label for="block_in_rest_1-1"><input type="radio" name="rest_buddy_option_name[block_in_rest_1]" id="block_in_rest_1-1" value="No" <?php echo $checked; ?>> No</label>
        </fieldset> <?php
                }

                public function featured_image_in_rest_2_callback()
                {
                    ?> <fieldset><?php $checked = (isset($this->rest_buddy_options['featured_image_in_rest_2']) && $this->rest_buddy_options['featured_image_in_rest_2'] === 'Yes') ? 'checked' : ''; ?>
            <label for="featured_image_in_rest_2-0"><input type="radio" name="rest_buddy_option_name[featured_image_in_rest_2]" id="featured_image_in_rest_2-0" value="Yes" <?php echo $checked; ?>> Yes</label><br>
            <?php $checked = (isset($this->rest_buddy_options['featured_image_in_rest_2']) && $this->rest_buddy_options['featured_image_in_rest_2'] === 'No') ? 'checked' : ''; ?>
            <label for="featured_image_in_rest_2-1"><input type="radio" name="rest_buddy_option_name[featured_image_in_rest_2]" id="featured_image_in_rest_2-1" value="No" <?php echo $checked; ?>> No</label>
        </fieldset> <?php
                }
            }
            if (is_admin())
                $rest_buddy = new RESTBuddy();

/*
 * Retrieve this value with:
 * $rest_buddy_options = get_option( 'rest_buddy_option_name' ); // Array of All Options
 * $menus_in_public_rest_0 = $rest_buddy_options['menus_in_public_rest_0']; // Menus in public REST
 * $block_in_rest_1 = $rest_buddy_options['block_in_rest_1']; // Block in REST
 * $featured_image_in_rest_2 = $rest_buddy_options['featured_image_in_rest_2']; // Featured Image in REST
 */
?>